#!/bin/bash
set -e
ci=$(realpath $(dirname $0))
newv=$1
if [ "$newv" = "" ]; then
  echo "$0 <version>"
  exit 1
fi

tee version/version.go << EOF
/* This file is autogenerated by GitHub Actions, do not change it manually. */
package version

var Version = "$newv"
EOF

sed -n "1,9p" CHANGELOG.md > CHANGELOG.md2
printf "## v$newv - $(date +%F)\n\n" >> CHANGELOG.md2
$ci/changelog-generate.sh >> CHANGELOG.md2
sed "1,9d" CHANGELOG.md >> CHANGELOG.md2
mv CHANGELOG.md2 CHANGELOG.md
