name: Release

on:
  pull_request:
    branches:
    - develop
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, '<release>')
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0

      - name: Extract version
        id: extract-version
        run: |
          version=$(echo "${{ github.event.pull_request.title }}" | grep -o -P '<release>:?\s*(\d+\.\d+\.\d+)(-\S+)?' |sed -E 's/<release>:?\s*//')
          echo $version
          echo ::set-output name=version::$version

      - name: Generate Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./ci/release.sh ${{ steps.extract-version.outputs.version }}
          
      - name: Commit and Tag
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: develop
          skip_fetch: true
          skip_checkout: true
          commit_message: "release: v${{ steps.extract-version.outputs.version }}"
          file_pattern: version/version.go CHANGELOG.md
          tagging_message: 'v${{ steps.extract-version.outputs.version }}'

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract-version.outputs.version }}
          body_path: CHANGELOG.tmp
      
      - name: Post Release
        run: |
          ./ci/post-release.sh
